apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrations
spec:
  ttlSecondsAfterFinished: 100
  template:
    metadata:
      labels:
        app: db-migration
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox:latest
          command: ["sh", "-c"]
          args:
            - |
              until nc -vz postgresql.default 5432; do
                echo "Waiting for db"
                sleep 2
              done
      containers:
        - name: db-migration-runner
          image: backend:latest
          command: ["sh", "-c"]
          # The command is running the migration, the env variables should be set beforehand
          args:
            - |
              export DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}.${POSTGRES_NAMESPACE}:${POSTGRES_PORT}/${POSTGRES_DB} && npm run migrate up
          env:
            - name: POSTGRES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POSTGRES_HOST
              value: "postgresql"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: "dnd"
            - name: POSTGRES_USER
              value: "dnd"
            - name: POSTGRES_PASSWORD
              value: "password"
          resources:
            limits:
              cpu: "100m"
              memory: "128Mi"
      restartPolicy: Never
