apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: dnd-manager
build:
  local:
    concurrency: 0
    tryImportMissing: false
    useDockerCLI: false
  artifacts:
    - image: hegepi/pg-graphql-postgres
      context: pg-graphql-postgres
      docker:
        dockerfile: Dockerfile
    - image: hegepi/backend
      context: backend
      docker:
        dockerfile: Dockerfile
    - image: hegepi/frontend
      context: frontend
      docker:
        dockerfile: Dockerfile
    - image: hegepi/db-migrations
      context: db-migrations
      docker:
        dockerfile: Dockerfile
    - image: hegepi/dnd-manager-graphiql
      context: graphiql
      docker: 
        dockerfile: Dockerfile

profiles:
  - name: dev
    deploy:
      helm:
        releases:
          - name: postgres-stack
            chartPath: k8s/helm/charts/postgres-stack
            valuesFiles:
              - k8s/helm/values/postgres-stack/values.dev.yaml
          - name: backend
            chartPath: k8s/helm/charts/backend
            valuesFiles:
              - "k8s/helm/values/backend/values.dev.yaml"
          - name: frontend
            chartPath: k8s/helm/charts/frontend
            valuesFiles:
              - "k8s/helm/values/frontend/values.dev.yaml"
          - name: db-migrations
            chartPath: k8s/helm/charts/db-migrations
            valuesFiles:
              - "k8s/helm/values/db-migrations/values.dev.yaml"
          - name: graphiql
            chartPath: k8s/helm/charts/graphiql
            valuesFiles:
              - "k8s/helm/values/graphiql/values.dev.yaml"
    portForward:
      - resourceType: service
        resourceName: postgres-stack-postgrest
        namespace: default
        port: 3000
        localPort: 3000
      - resourceType: service
        resourceName: graphiql
        namespace: default
        port: 80
        localPort: 3002
      - resourceType: service
        resourceName: frontend
        namespace: default
        port: 3100
        localPort: 3100

  - name: prod
    deploy:
      helm:
        releases:
          - name: postgres-stack
            chartPath: k8s/helm/charts/postgres-stack
            valuesFiles:
              - k8s/helm/values/postgres-stack/values.prod.yaml
          - name: backend
            chartPath: k8s/helm/charts/backend
            valuesFiles:
              - "k8s/helm/values/backend/values.prod.yaml"
          - name: frontend
            chartPath: k8s/helm/charts/frontend
            valuesFiles:
              - "k8s/helm/values/frontend/values.prod.yaml"
          - name: db-migrations
            chartPath: k8s/helm/charts/db-migrations
            valuesFiles:
              - "k8s/helm/values/db-migrations/values.prod.yaml"
