apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: dnd-manager
build:
  artifacts:
    - image: backend
      context: backend
      docker:
        dockerfile: Dockerfile
    - image: svelte-frontend
      context: svelte-frontend
      docker:
        dockerfile: Dockerfile
manifests:
  kustomize:
    paths:
      - dev
profiles:
  - name: .
    manifests:
      kustomize:
        paths:
          - .
