migration:
  enabled: true

image:
  repository: hegepi/dbmigration
  tag: latest
  pullPolicy: IfNotPresent

postgres:
  host: postgres-stack-postgres
  port: "5432"
  user: changeme-default-user-dnd
  password: changeme-default-password-dnd
  database: changeme-default-db-dnd