migration:
  enabled: true

image:
  repository: hegepi/dbmigration
  tag: latest
  pullPolicy: IfNotPresent

postgres:
  host: postgres-stack-postgres-stack-postgres
  port: "5432"
  user: changeme-default-dnd
  password: changeme-default-password
  database: changeme-default-dnd