replicaCount: 1

postgres:
  image:
    repository: hegepi/pg-graphql-postgres
    tag: latest
    pullPolicy: IfNotPresent
  postgresUser: changeme-default-user-dnd
  postgresPassword: changeme-default-password-dnd
  postgresDatabase: changeme-default-db-dnd
  persistence:
    enabled: true
    storageClass: ""
    accessModes:
      - ReadWriteOnce
    size: 1Gi
  # Pod security context values (match the UID/GID in your custom image)
  securityContext:
    runAsUser: 1001
    runAsGroup: 1001
    fsGroup: 1001
    
postgrest:
  enabled: true
  image:
    repository: postgrest/postgrest
    tag: latest
    pullPolicy: IfNotPresent
  dbAnonRole: anon
  # PGRST_DB_URI will be templated from postgres service
  dbSchemas: public,graphql

service:
  postgres:
    port: 5432
    type: ClusterIP
  postgrest:
    port: 3000
    type: ClusterIP

ingress:
  enabled: false
  host: postgrest.local

resources: {}
