apiVersion: apps/v1
kind: Deployment
metadata:
  name: svelte-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: svelte-frontend
  template:
    metadata:
      labels:
        app: svelte-frontend
    spec:
      containers:
        - name: svelte-frontend-container
          image: svelte-frontend
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: "1"
              memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: svelte-frontend
spec:
  selector:
    app: svelte-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
