apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "postgrest.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "postgrest.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "postgrest.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "postgrest.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: postgrest
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
          env:
            - name: PGRST_DB_URI
              value: "{{ .Values.env.dbUri }}"
            - name: PGRST_DB_ANON_ROLE
              value: "{{ .Values.env.dbAnonRole }}"
            - name: PGRST_DB_SCHEMAS
              value: "{{ .Values.env.dbSchemas }}"
            - name: PGRST_SERVER_PORT
              value: "{{ tpl (toString .Values.service.port) . }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
