# Put postgrest secrets into a Kubernetes Secret
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres-stack.fullname" . }}-postgrest-secrets
  labels:
    app.kubernetes.io/name: {{ include "postgres-stack.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  # db-uri is still malformed, postgres://changeme-default-user-dnd:changeme-default-password-dnd@postgres-stack-postgres:%!d(float64=5432)/changeme-default-db-dnd, fix it
  db-uri: {{ printf "postgres://%s:%s@%s-postgres:%d/%s" .Values.postgres.postgresUser .Values.postgres.postgresPassword (include "postgres-stack.fullname" .) (int .Values.service.postgres.port) .Values.postgres.postgresDatabase | b64enc }}
  db-schemas: {{ .Values.postgrest.dbSchemas | b64enc }}
  db-anon-role: {{ .Values.postgrest.dbAnonRole | b64enc }}