primary:
  resources:
    limits:
      cpu: 1
      memory: 1024Mi

readReplicas:
  resources:
    limits:
      cpu: 1
      memory: 1024Mi

backup:
  cronjob:
    resources:
      limits:
        cpu: 1
        memory: 1024Mi

volumePermissions:
  resources:
    cpu: 1
    memory: 1024Mi
