{{- if .Values.migration.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "db-migration.fullname" . }}-job
  labels:
    app.kubernetes.io/name: {{ include "db-migration.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  template:
    metadata:
      labels:
        app: {{ include "db-migration.fullname" . }}-job
    spec:
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "db-migration.serviceAccountName" . }}
      {{- end }}
      restartPolicy: OnFailure
      containers:
        - name: db-migration
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          command:
            - sh
            - -c
            - |
              set -ex
              echo "Starting database migration..."
              # Wait for Postgres to be ready. use busybox to check whether db is ready
              until nc -z -v -w30 $POSTGRES_HOST $POSTGRES_PORT
              do
                echo "Waiting for database connection..."
                sleep 5
              done
              echo "Database is up - executing migration scripts"

              DATABASE_URL="postgresql://$POSTGRES_USER:$PGPASSWORD@$POSTGRES_HOST:$POSTGRES_PORT/$POSTGRES_DATABASE" bun run migrate up
              echo "Database migration completed successfully"
          securityContext: {{ toYaml .Values.securityContext | nindent 12 }}
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "db-migration.fullname" . }}-db-credentials
                  key: postgres-user
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "db-migration.fullname" . }}-db-credentials
                  key: postgres-password
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ include "db-migration.fullname" . }}-db-credentials
                  key: postgres-host
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ include "db-migration.fullname" . }}-db-credentials
                  key: postgres-port
            - name: POSTGRES_DATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ include "db-migration.fullname" . }}-db-credentials
                  key: postgres-database
{{- end }}

