# Create secret helm template that stores database credentials for db-migration job
{{- if .Values.migration.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "db-migration.fullname" . }}-db-credentials
  labels:
    app.kubernetes.io/name: {{ include "db-migration.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  postgres-user: {{ .Values.postgres.user | b64enc }}
  postgres-password: {{ .Values.postgres.password | b64enc }}
  postgres-host: {{ .Values.postgres.host | b64enc }}
  postgres-port: {{ .Values.postgres.port | b64enc }}
  postgres-database: {{ .Values.postgres.database | b64enc }}
{{- end }}